// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTextSplit from '@/components/sections/about/AboutTextSplit';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTextSplit
          title="The Broadway Black Cars Standard"
          descriptions={[
            "Broadway Black Cars brings a bespoke touch to Nashville transportation. With a background in elite service, every journey is curated for maximum comfort and complete punctuality.",
            "Forget ride-share unpredictability. You are guaranteed a pristine vehicle, a professional driver, and a seamless travel experience designed for the discerning individual.",
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
