// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
        tag="Book Your Chauffeur"
        text="Secure your private luxury car today. Experience the Broadway Black Cars difference. Call or text us at 615-339-2522."
        primaryButton={{"text":"Call or Text: 615-339-2522","href":"sms:+16153392522"}}
        secondaryButton={{
            text: "Email for Reservations",
            href: "mailto:reservations@safinnashville.com",
          }}
      />
        </SectionErrorBoundary>
      </div>
  );
}
