// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Book Your Chauffeur"
          text="Secure your private luxury car today. Experience the Broadway Black Cars difference."
          primaryButton={{
            text: "Text Broadway Black Cars Now",
            href: "sms:+16155550123",
          }}
          secondaryButton={{
            text: "Email for Reservations",
            href: "mailto:reservations@safinnashville.com",
          }}
        />
        </SectionErrorBoundary>
      </div>
  );
}
