// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesTaggedCards from '@/components/sections/features/FeaturesTaggedCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
        <SectionErrorBoundary name="features">
              <FeaturesTaggedCards
          tag="Our Commitment"
          title="Uncompromised Quality"
          description="The hallmarks of a luxury chauffeur service."
          items={[
            {
              tag: "Discretion",
              title: "Total Privacy",
              description: "Whether you are traveling for business or leisure, your ride is your private sanctuary.",
              primaryButton: {
                text: "Learn More",
                href: "#",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/woman-enjoying-her-financially-independence-while-buying-car_23-2149434394.jpg",
            },
            {
              tag: "Comfort",
              title: "Pristine Interiors",
              description: "Every vehicle is inspected and detailed to ensure a flawless presentation.",
              primaryButton: {
                text: "Learn More",
                href: "#",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/focused-manly-woman-is-doing-car-diagnostic-with-computer-help-auto-service_613910-17108.jpg",
            },
            {
              tag: "Reliability",
              title: "Punctual Performance",
              description: "We understand that time is your most valuable asset. We are always ready before you.",
              primaryButton: {
                text: "Learn More",
                href: "#",
              },
              imageSrc: "http://img.b2bpic.net/free-photo/young-woman-standing-with-suitcase-parking_23-2148328862.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
