// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroOverlay from '@/components/sections/hero/HeroOverlay';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroOverlay
          tag="Nashville's Premier Chauffeur"
          title="Where Exceptional Driving Meets Luxury"
          description="Experience the pinnacle of black car service. Broadway Black Cars provides unmatched reliability, discretion, and comfort in every mile."
          primaryButton={{
            text: "Reserve Your Ride",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Learn More",
            href: "#about",
          }}
          imageSrc="http://img.b2bpic.net/free-photo/business-woman-car_1303-3812.jpg"
        />
        </SectionErrorBoundary>
      </div>
  );
}
