// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsMediaCards from '@/components/sections/metrics/MetricsMediaCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsMediaCards
          tag="Proven Track Record"
          title="By The Numbers"
          description="Excellence defined through performance."
          metrics={[
            {
              value: "100%",
              title: "On-Time Arrival",
              description: "Reliability you can stake your schedule on.",
              imageSrc: "http://img.b2bpic.net/free-photo/woman-enjoying-her-financially-independence-while-buying-car_23-2149434364.jpg",
            },
            {
              value: "500+",
              title: "Satisfied Guests",
              description: "Trusted by Nashville's elite professionals.",
              imageSrc: "http://img.b2bpic.net/free-photo/business-woman-with-phone-car_1303-3840.jpg",
            },
            {
              value: "24/7",
              title: "Service Availability",
              description: "Your schedule is our only priority.",
              imageSrc: "http://img.b2bpic.net/free-photo/white-retro-car-new-limousine-ride-along-street-new-york_8353-1464.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
