// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "social-proof" section.

import React from 'react';
import SocialProofMarquee from '@/components/sections/social-proof/SocialProofMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SocialProofSection(): React.JSX.Element {
  return (
    <div id="social-proof" data-section="social-proof">
        <SectionErrorBoundary name="social-proof">
              <SocialProofMarquee
          tag="Trusted Partner"
          title="Servicing Nashville's Top Destinations"
          description="We are the preferred choice for business leaders and discerning travelers."
          names={[
            "Opryland Resort",
            "Nashville International",
            "The Gulch",
            "Bridgestone Arena",
            "Music Row",
            "Downtown Nashville",
            "Brentwood",
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
