// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialQuoteCards from '@/components/sections/testimonial/TestimonialQuoteCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialQuoteCards
          tag="Client Experience"
          title="Luxury in Every Detail"
          description="Don't just take our word for it—hear from those who prioritize quality."
          testimonials={[
            {
              name: "James Henderson",
              role: "CEO, TechCorp",
              quote: "Broadway Black Cars has transformed my commute. It's not just a ride; it's a calm moment in a busy schedule.",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-adult-businesswoman-smiling_23-2148452640.jpg",
            },
            {
              name: "Elena Rodriguez",
              role: "Venture Capitalist",
              quote: "The professionalism is unmatched in Nashville. I wouldn't dream of using anyone else.",
              imageSrc: "http://img.b2bpic.net/free-photo/joyful-business-woman-with-coffee-cup_23-2148095746.jpg",
            },
            {
              name: "Marcus Thorne",
              role: "Entertainment Attorney",
              quote: "Exceptional driving, spotless vehicle, and the utmost discretion. A true class act.",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-mature-businessman-using-digital-tablet-caf_23-2147955292.jpg",
            },
            {
              name: "Sarah Jenkins",
              role: "Design Director",
              quote: "Broadway Black Cars is always on time, polite, and the car is pristine every single time.",
              imageSrc: "http://img.b2bpic.net/free-photo/young-businesswoman-portrait-office_1262-1506.jpg",
            },
            {
              name: "David Wu",
              role: "Consulting Partner",
              quote: "The reliability is stellar. It's the most stress-free way to navigate the city.",
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-portrait-handsome-confident-middle-aged-businessman-black-background_176420-5560.jpg",
            },
          ]}
        />
        </SectionErrorBoundary>
      </div>
  );
}
